version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/Minigames"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/Regions"
    schedule:
      interval: "weekly"
