name: Minigames-Regions
main: au.com.mineauz.minigamesregions.Main
version: ${plugin.version}
api-version: "${paper.api.version}"
author: _Razz_ AddstarMC GreenSurvivors
depend: [ 'Minigames' ]
description: ${project.description}